services:
  app:
    build:
      context: .
    environment:
      DATABASE_CONNECTION_STRING: ${DATABASE_CONNECTION_STRING}
      ENVIRONMENT: ${ENVIRONMENT}
      SERVER_HOST: ${SERVER_HOST}
      VITE_BASE_URL: ${VITE_BASE_URL}
      MAIL_SMTP_HOST: ${MAIL_SMTP_HOST}
      MAIL_SMTP_USER: ${MAIL_SMTP_USER}
      MAIL_SMTP_PASSWORD: ${MAIL_SMTP_PASSWORD}
      MAIL_FROM_NAME: ${MAIL_FROM_NAME}
      MAIL_FROM_ADDRESS: ${MAIL_FROM_ADDRESS}
      BETTER_AUTH_SECRET: ${BETTER_AUTH_SECRET}

    depends_on:
      postgres:
        condition: service_started
    networks:
      - statusline-network
  postgres:
    image: postgres:18-alpine3.23
    restart: on-failure
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - statusline_postgres:/var/lib/postgresql
    networks:
      - statusline-network

volumes:
  statusline_postgres:
networks:
  statusline-network:
