/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './pages/__root'
import { Route as StatusRouteImport } from './pages/status'
import { Route as RegistrierenRouteImport } from './pages/registrieren'
import { Route as DashboardRouteImport } from './pages/dashboard'
import { Route as AnmeldenRouteImport } from './pages/anmelden'
import { Route as IndexRouteImport } from './pages/index'
import { Route as DashboardIndexRouteImport } from './pages/dashboard/index'
import { Route as DashboardStatusSequenzRouteImport } from './pages/dashboard/status-sequenz'
import { Route as DashboardAuftraegeRouteImport } from './pages/dashboard/auftraege'

const StatusRoute = StatusRouteImport.update({
  id: '/status',
  path: '/status',
  getParentRoute: () => rootRouteImport,
} as any)
const RegistrierenRoute = RegistrierenRouteImport.update({
  id: '/registrieren',
  path: '/registrieren',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AnmeldenRoute = AnmeldenRouteImport.update({
  id: '/anmelden',
  path: '/anmelden',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardStatusSequenzRoute = DashboardStatusSequenzRouteImport.update({
  id: '/status-sequenz',
  path: '/status-sequenz',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAuftraegeRoute = DashboardAuftraegeRouteImport.update({
  id: '/auftraege',
  path: '/auftraege',
  getParentRoute: () => DashboardRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/anmelden': typeof AnmeldenRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/registrieren': typeof RegistrierenRoute
  '/status': typeof StatusRoute
  '/dashboard/auftraege': typeof DashboardAuftraegeRoute
  '/dashboard/status-sequenz': typeof DashboardStatusSequenzRoute
  '/dashboard/': typeof DashboardIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/anmelden': typeof AnmeldenRoute
  '/registrieren': typeof RegistrierenRoute
  '/status': typeof StatusRoute
  '/dashboard/auftraege': typeof DashboardAuftraegeRoute
  '/dashboard/status-sequenz': typeof DashboardStatusSequenzRoute
  '/dashboard': typeof DashboardIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/anmelden': typeof AnmeldenRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/registrieren': typeof RegistrierenRoute
  '/status': typeof StatusRoute
  '/dashboard/auftraege': typeof DashboardAuftraegeRoute
  '/dashboard/status-sequenz': typeof DashboardStatusSequenzRoute
  '/dashboard/': typeof DashboardIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/anmelden'
    | '/dashboard'
    | '/registrieren'
    | '/status'
    | '/dashboard/auftraege'
    | '/dashboard/status-sequenz'
    | '/dashboard/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/anmelden'
    | '/registrieren'
    | '/status'
    | '/dashboard/auftraege'
    | '/dashboard/status-sequenz'
    | '/dashboard'
  id:
    | '__root__'
    | '/'
    | '/anmelden'
    | '/dashboard'
    | '/registrieren'
    | '/status'
    | '/dashboard/auftraege'
    | '/dashboard/status-sequenz'
    | '/dashboard/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AnmeldenRoute: typeof AnmeldenRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  RegistrierenRoute: typeof RegistrierenRoute
  StatusRoute: typeof StatusRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/status': {
      id: '/status'
      path: '/status'
      fullPath: '/status'
      preLoaderRoute: typeof StatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/registrieren': {
      id: '/registrieren'
      path: '/registrieren'
      fullPath: '/registrieren'
      preLoaderRoute: typeof RegistrierenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/anmelden': {
      id: '/anmelden'
      path: '/anmelden'
      fullPath: '/anmelden'
      preLoaderRoute: typeof AnmeldenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/status-sequenz': {
      id: '/dashboard/status-sequenz'
      path: '/status-sequenz'
      fullPath: '/dashboard/status-sequenz'
      preLoaderRoute: typeof DashboardStatusSequenzRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/auftraege': {
      id: '/dashboard/auftraege'
      path: '/auftraege'
      fullPath: '/dashboard/auftraege'
      preLoaderRoute: typeof DashboardAuftraegeRouteImport
      parentRoute: typeof DashboardRoute
    }
  }
}

interface DashboardRouteChildren {
  DashboardAuftraegeRoute: typeof DashboardAuftraegeRoute
  DashboardStatusSequenzRoute: typeof DashboardStatusSequenzRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardAuftraegeRoute: DashboardAuftraegeRoute,
  DashboardStatusSequenzRoute: DashboardStatusSequenzRoute,
  DashboardIndexRoute: DashboardIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AnmeldenRoute: AnmeldenRoute,
  DashboardRoute: DashboardRouteWithChildren,
  RegistrierenRoute: RegistrierenRoute,
  StatusRoute: StatusRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.ts'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
